#!/usr/bin/env python3
"""Rebuild the apps: embed the scenario data and the shared code block.

The apps are single self-contained HTML files opened straight from disk. A page
on file:// cannot fetch a JSON file next to it, and a <script src> to a sibling
file is refused by some browsers, so both the data and the shared code are
copied into each app by this script.

Two injections, both idempotent, both anchored on a comment the HTML declares
itself, so this script needs no map of what goes where.

  1. the data line

     const DATA = [...];  // embedded by tools/build_apps.py from data/foo.json

  2. the shared block, from tools/shared/aipm.js

     // begin shared block: tools/shared/aipm.js
     ... copied code ...
     // end shared block: tools/shared/aipm.js

Usage:
    python3 tools/build_apps.py           rebuild every app in place
    python3 tools/build_apps.py --check   exit 1 if any app is out of date

Run it after editing tools/shared/aipm.js or anything under data/.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Accepts the old embed_data.py comment too, so nothing breaks on first run,
# and rewrites it to the new one.
DATA_LINE = re.compile(
    r"^const DATA = .*;\s*// embedded by tools/(?:embed_data|build_apps)\.py from (\S+)$",
    re.MULTILINE,
)

SHARED_BLOCK = re.compile(
    r"^// begin shared block: (\S+)$.*?^// end shared block: \1$",
    re.MULTILINE | re.DOTALL,
)


def rebuild(html):
    """Return the rebuilt html and a list of what changed."""
    changed = []

    match = DATA_LINE.search(html)
    if match:
        source = match.group(1)
        payload = json.dumps(
            json.loads((ROOT / source).read_text()), ensure_ascii=False
        )
        line = f"const DATA = {payload};  // embedded by tools/build_apps.py from {source}"
        if line != match.group(0):
            changed.append(f"data from {source}")
        html = html[: match.start()] + line + html[match.end():]

    match = SHARED_BLOCK.search(html)
    if match:
        source = match.group(1)
        body = (ROOT / source).read_text().rstrip("\n")
        block = (
            f"// begin shared block: {source}\n"
            f"// Generated by tools/build_apps.py. Edit {source}, never this copy.\n"
            f"{body}\n"
            f"// end shared block: {source}"
        )
        if block != match.group(0):
            changed.append(f"shared block from {source}")
        html = html[: match.start()] + block + html[match.end():]

    return html, changed


def main():
    check = "--check" in sys.argv
    stale = []

    targets = sorted(ROOT.glob("apps/index.html")) + sorted(ROOT.glob("apps/*/index.html"))
    for path in targets:
        original = path.read_text()
        rebuilt, changed = rebuild(original)
        rel = path.relative_to(ROOT)

        if not changed:
            print(f"ok     {rel}")
            continue

        if check:
            stale.append(rel)
            print(f"STALE  {rel}: {', '.join(changed)}")
        else:
            path.write_text(rebuilt)
            print(f"wrote  {rel}: {', '.join(changed)}")

    if check and stale:
        print(f"\n{len(stale)} app(s) out of date. Run: python3 tools/build_apps.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
